---
version: '3'
networks:
  freqtrade:
    external: true

services:
  proxy:
    build: .
    container_name: binance-proxy
    restart: unless-stopped
    networks:
      - freqtrade
    ports:
      - ${KUCOIN_PROXY_PORT}:8080
